# Don't forget to import all the classifiers
# and transformers you want to use
classifiers:
  # - name: SVC
  #   steps:
  #     - name: SVC

  # - name: KNeighborsClassifier
  #   steps:
  #     - name: PCA # hamming distance
  #     - name: KNeighborsClassifier

  # - name:  GaussianNB
  #   steps:
  #     - name: PCA
  #     - name: GaussianNB

  # - name: AdaBoostClassifier
  #   steps:
  #     # - name: PCA
  #     - name: AdaBoostClassifier

  # - name: MLPClassifier
  #   steps:
  #     - name: PCA
  #       args:
  #         n_components: [0.95]
  #     - name: MLPClassifier

  # - name: RandomForestClassifier
  #   steps:
  #     # - name: PCA
  #     - name: RandomForestClassifier
  #       args:
  #         n_estimators: [100, 150] # default = 100

  - name: XGBClassifier
    steps:
#      - name: PCA
      # - name: VarianceThreshold
#      - name: NMF
#        args:
#          n_components: [50]
##          init: ['nndsvd']
#          beta_loss: ['frobenius', 0.1, 0.8]
#          solver: ['mu']
      - name: XGBClassifier
        args:
          n_estimators: [100] # [100, 150, 200] # default = 100
          tree_method: ['gpu_hist']

#-   name: KNeighborsClassifier
#    steps:
##      - name: PCA
#      # - name: VarianceThreshold
##      - name: NMF
##        args:
##          n_components: [50]
###          init: ['nndsvd']
##          beta_loss: ['frobenius', 0.1, 0.8]
##          solver: ['mu']
#      - name: KNeighborsClassifier
